/*
 * CSOLUTION generated file: DO NOT EDIT!
 * Generated by: csolution version 2.6.0
 *
 * Project: 'firmware-alif.Debug+HP_DEVKIT' 
 * Target:  'Debug+HP_DEVKIT' 
 */

#ifndef RTE_COMPONENTS_H
#define RTE_COMPONENTS_H


/*
 * Define the Device Header File: 
 */
#define CMSIS_device_header "M55_HP.h"

/* ARM::RTOS&FreeRTOS:Config&FreeRTOS@10.5.1 */
#define RTE_RTOS_FreeRTOS_CONFIG        /* RTOS FreeRTOS Config for FreeRTOS API */
/* ARM::RTOS&FreeRTOS:Core&Cortex-M@10.5.1 */
#define RTE_RTOS_FreeRTOS_CORE          /* RTOS FreeRTOS Core */
/* ARM::RTOS&FreeRTOS:Event Groups@10.5.1 */
#define RTE_RTOS_FreeRTOS_EVENTGROUPS   /* RTOS FreeRTOS Event Groups */
/* ARM::RTOS&FreeRTOS:Heap&Heap_4@10.5.1 */
#define RTE_RTOS_FreeRTOS_HEAP_4        /* RTOS FreeRTOS Heap 4 */
/* ARM::RTOS&FreeRTOS:Timers@10.5.1 */
#define RTE_RTOS_FreeRTOS_TIMERS        /* RTOS FreeRTOS Timers */
/* AlifSemiconductor::BSP:External peripherals:CAMERA Sensor MT9M114@1.3.0 */
#define RTE_Drivers_CAMERA_SENSOR_MT9M114   1           /* Driver CAMERA Sensor */
/* AlifSemiconductor::BSP:External peripherals:ILI9806E LCD panel@1.3.0 */
#define RTE_Drivers_MIPI_DSI_ILI9806E_PANEL 1   /* Driver ILI9806E LCD panel*/
/* AlifSemiconductor::Device:SOC Peripherals:CDC@1.3.0 */
#define RTE_Drivers_CDC200 1   /* Driver CDC200*/
/* AlifSemiconductor::Device:SOC Peripherals:CPI@1.3.0 */
#define RTE_Drivers_CPI   1           /* Driver CAMERA Controller */
/* AlifSemiconductor::Device:SOC Peripherals:DMA@1.3.0 */
#define RTE_Drivers_DMA 1   /* Driver DMA*/
/* AlifSemiconductor::Device:SOC Peripherals:GPIO@1.3.0 */
#define RTE_Drivers_GPIO   1           /* Driver GPIO */
/* AlifSemiconductor::Device:SOC Peripherals:I2C@1.3.0 */
#define RTE_Drivers_I2C   1           /* Driver I2C */
/* AlifSemiconductor::Device:SOC Peripherals:I2S@1.3.0 */
#define RTE_Drivers_SAI   1           /* Driver SAI */
/* AlifSemiconductor::Device:SOC Peripherals:I3C@1.3.0 */
#define RTE_Drivers_I3C0   1           /* Driver I3C */
/* AlifSemiconductor::Device:SOC Peripherals:MIPI CSI2@1.3.0 */
#define RTE_Drivers_MIPI_CSI2   1   /* Driver MIPI CSI2 */
/* AlifSemiconductor::Device:SOC Peripherals:MIPI DSI CSI2 DPHY@1.3.0 */
#define RTE_Drivers_MIPI_DSI_CSI2_DPHY   1   /* Driver DPHY */
/* AlifSemiconductor::Device:SOC Peripherals:MIPI DSI@1.3.0 */
#define RTE_Drivers_MIPI_DSI   1   /* Driver MIPI DSI */
/* AlifSemiconductor::Device:SOC Peripherals:PINCONF@1.3.0 */
#define RTE_Drivers_LL_PINCONF   1           /* Driver PinPAD and PinMux */
/* AlifSemiconductor::Device:SOC Peripherals:USART@1.3.0 */
#define RTE_Drivers_USART0   1           /* Driver UART0 */
#define RTE_Drivers_USART1   1           /* Driver UART1 */
#define RTE_Drivers_USART2   1           /* Driver UART2 */
#define RTE_Drivers_USART3   1           /* Driver UART3 */
#define RTE_Drivers_USART4   1           /* Driver UART4 */
#define RTE_Drivers_USART5   1           /* Driver UART5 */
#define RTE_Drivers_USART6   1           /* Driver UART6 */
#define RTE_Drivers_USART7   1           /* Driver UART7 */
/* AlifSemiconductor::Device:SOC Peripherals:UTIMER@1.3.0 */
#define RTE_Drivers_UTIMER   1           /* Driver UTIMER */
/* Arm::Machine Learning:NPU Support:Ethos-U Driver&Generic U55@1.24.11 */
#define RTE_ETHOS_U_CORE_DRIVER


#endif /* RTE_COMPONENTS_H */
